import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/Layout';
import { useRecoilState, useRecoilValue } from 'recoil';
import { postsListState } from '../store/posts';
import PostForm from '../components/Post/PostForm';

const Home: NextPage = () => {
  const postsList = useRecoilValue(postsListState);

  console.log('포스트 리스트: ', postsList);

  return (
    <Layout>
      <Head>
        <title>Murmur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl font-bold text-indigo-600">Hello World</h1>
      <PostForm />
    </Layout>
  );
};

export default Home;
