import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/Layout';
import { useRecoilValue, useSetRecoilState } from 'recoil';
import { dummyData, postsListState } from '../store/posts';
import PostForm from '../components/Post/PostForm';
import PostCard from '../components/Post/PostCard';
import { MutableRefObject, useCallback, useRef } from 'react';
import useIntersectionObserver from '../hooks/useIntersectionObserver';

const Home: NextPage = () => {
  const postsList = useRecoilValue(postsListState);
  const setPostsList = useSetRecoilState(postsListState);

  const loadMoreRef: MutableRefObject<HTMLDivElement | null> = useRef(null);

  const handleLoadMore = useCallback(() => {
    console.log('더 보기');
    const extraData = dummyData();
    setPostsList((prev) => [...prev, ...extraData]);
  }, [setPostsList]);

  useIntersectionObserver({
    target: loadMoreRef,
    onIntersect: handleLoadMore,
    threshold: 0.25,
  });

  return (
    <Layout>
      <Head>
        <title>Murmur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostForm />

      <div className="mt-4">
        {postsList.map((post) => (
          <PostCard key={post.id} post={post} />
        ))}
        <div ref={loadMoreRef} className="my-4 bg-white ">
          <button onClick={handleLoadMore}>더 보기</button>
        </div>
      </div>
    </Layout>
  );
};

export default Home;
